<?
$PERM["admin"]["3"]="R";
$PERM["admin"]["4"]="R";
$PERM["admin"]["6"]="R";
$PERM["admin"]["7"]="R";
$PERM["admin"]["8"]="R";
$PERM["admin"]["16"]="R";
$PERM["admin"]["10"]="R";
$PERM["admin"]["11"]="R";
$PERM["admin"]["17"]="R";
$PERM["admin"]["19"]="R";
$PERM["admin"]["12"]="R";
$PERM["admin"]["14"]="R";
$PERM["admin"]["15"]="R";
$PERM["admin"]["13"]="R";
$PERM["admin"]["18"]="R";
$PERM["admin"]["9"]="R";
$PERM["admin"]["20"]="R";
$PERM["admin"]["*"]="D";
$PERM["wizards"]["*"]="D";
?>